# permissions for end users to view ciscocrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ciscocrd-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cisco
    app.kubernetes.io/part-of: cisco
    app.kubernetes.io/managed-by: kustomize
  name: ciscocrd-viewer-role
rules:
- apiGroups:
  - cisco.kind-kind
  resources:
  - ciscocrds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cisco.kind-kind
  resources:
  - ciscocrds/status
  verbs:
  - get
