---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cisco.kind-kind
  resources:
  - ciscocrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cisco.kind-kind
  resources:
  - ciscocrds/finalizers
  verbs:
  - update
- apiGroups:
  - cisco.kind-kind
  resources:
  - ciscocrds/status
  verbs:
  - get
  - patch
  - update
